// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {config} from '../models';
import {main} from '../models';

export function AcceptFriendRequest(arg1:string):Promise<void>;

export function AcceptPartyInvite(arg1:string):Promise<void>;

export function AddFriend(arg1:string):Promise<void>;

export function CancelFriendRequest(arg1:string):Promise<void>;

export function CancelPartyInvite(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function ClearLogs():Promise<void>;

export function ClearManualMapOverride():Promise<void>;

export function ConnectToPartyServer(arg1:string):Promise<void>;

export function CreateCentralParty():Promise<string>;

export function Debug(arg1:string):Promise<void>;

export function DeclineFriendRequest(arg1:string):Promise<void>;

export function DeclinePartyInvite(arg1:string):Promise<void>;

export function DisconnectFromPartyServer():Promise<void>;

export function DownloadUpdate(arg1:string):Promise<void>;

export function Error(arg1:string):Promise<void>;

export function ExportLogs():Promise<string>;

export function GetAvailableMaps():Promise<Array<Record<string, string>>>;

export function GetCentralPartyMembers():Promise<Array<Record<string, any>>>;

export function GetCentralPartyStatus():Promise<Record<string, any>>;

export function GetConfig():Promise<config.Config>;

export function GetDataDir():Promise<string>;

export function GetDefaultLogsDir():Promise<string>;

export function GetDefaultScreenshotDir():Promise<string>;

export function GetFriends():Promise<Array<Record<string, any>>>;

export function GetIncomingFriendRequests():Promise<Array<Record<string, any>>>;

export function GetLogStats():Promise<Record<string, number>>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetOutgoingFriendRequests():Promise<Array<Record<string, any>>>;

export function GetPartyMembers():Promise<Array<Record<string, any>>>;

export function GetPartyServerInfo():Promise<Record<string, any>>;

export function GetPartyStatus():Promise<Record<string, any>>;

export function GetPendingFriendRequests():Promise<void>;

export function GetPendingInvites():Promise<Array<Record<string, any>>>;

export function GetPlatform():Promise<string>;

export function GetPublicIP():Promise<string>;

export function GetQuestProgress():Promise<any>;

export function GetStatus():Promise<Record<string, any>>;

export function GetUpdateStatus():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function Info(arg1:string):Promise<void>;

export function InjectPosition(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<void>;

export function InviteFriendToParty(arg1:string):Promise<void>;

export function IsRunning():Promise<boolean>;

export function JoinCentralParty(arg1:string):Promise<void>;

export function JoinParty(arg1:string,arg2:string):Promise<void>;

export function LeaveCentralParty():Promise<void>;

export function LeaveParty():Promise<void>;

export function OpenMapWindow():Promise<void>;

export function OpenReleaseURL():Promise<void>;

export function OpenTarkovDevBrowser():Promise<void>;

export function RemoveFriend(arg1:string):Promise<void>;

export function RestartApplication():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectLogsDirectory():Promise<string>;

export function SelectScreenshotDirectory():Promise<string>;

export function SendPositionToParty(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function SetAutoUpdateCheck(arg1:boolean):Promise<void>;

export function SetManualMapOverride(arg1:string):Promise<void>;

export function SetUpdateChannel(arg1:string):Promise<void>;

export function StartIntegration():Promise<void>;

export function StartPartyServer():Promise<string>;

export function StopIntegration():Promise<void>;

export function StopPartyServer():Promise<void>;

export function TestConnection():Promise<void>;

export function ValidateQuestToken():Promise<void>;

export function Warning(arg1:string):Promise<void>;
