// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriendRequest(arg1) {
  return window['go']['main']['App']['AcceptFriendRequest'](arg1);
}

export function AcceptPartyInvite(arg1) {
  return window['go']['main']['App']['AcceptPartyInvite'](arg1);
}

export function AddFriend(arg1) {
  return window['go']['main']['App']['AddFriend'](arg1);
}

export function CancelFriendRequest(arg1) {
  return window['go']['main']['App']['CancelFriendRequest'](arg1);
}

export function CancelPartyInvite(arg1) {
  return window['go']['main']['App']['CancelPartyInvite'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearManualMapOverride() {
  return window['go']['main']['App']['ClearManualMapOverride']();
}

export function ConnectToPartyServer(arg1) {
  return window['go']['main']['App']['ConnectToPartyServer'](arg1);
}

export function CreateCentralParty() {
  return window['go']['main']['App']['CreateCentralParty']();
}

export function Debug(arg1) {
  return window['go']['main']['App']['Debug'](arg1);
}

export function DeclineFriendRequest(arg1) {
  return window['go']['main']['App']['DeclineFriendRequest'](arg1);
}

export function DeclinePartyInvite(arg1) {
  return window['go']['main']['App']['DeclinePartyInvite'](arg1);
}

export function DisconnectFromPartyServer() {
  return window['go']['main']['App']['DisconnectFromPartyServer']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function Error(arg1) {
  return window['go']['main']['App']['Error'](arg1);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function GetAvailableMaps() {
  return window['go']['main']['App']['GetAvailableMaps']();
}

export function GetCentralPartyMembers() {
  return window['go']['main']['App']['GetCentralPartyMembers']();
}

export function GetCentralPartyStatus() {
  return window['go']['main']['App']['GetCentralPartyStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDefaultLogsDir() {
  return window['go']['main']['App']['GetDefaultLogsDir']();
}

export function GetDefaultScreenshotDir() {
  return window['go']['main']['App']['GetDefaultScreenshotDir']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetIncomingFriendRequests() {
  return window['go']['main']['App']['GetIncomingFriendRequests']();
}

export function GetLogStats() {
  return window['go']['main']['App']['GetLogStats']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOutgoingFriendRequests() {
  return window['go']['main']['App']['GetOutgoingFriendRequests']();
}

export function GetPartyMembers() {
  return window['go']['main']['App']['GetPartyMembers']();
}

export function GetPartyServerInfo() {
  return window['go']['main']['App']['GetPartyServerInfo']();
}

export function GetPartyStatus() {
  return window['go']['main']['App']['GetPartyStatus']();
}

export function GetPendingFriendRequests() {
  return window['go']['main']['App']['GetPendingFriendRequests']();
}

export function GetPendingInvites() {
  return window['go']['main']['App']['GetPendingInvites']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPublicIP() {
  return window['go']['main']['App']['GetPublicIP']();
}

export function GetQuestProgress() {
  return window['go']['main']['App']['GetQuestProgress']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Info(arg1) {
  return window['go']['main']['App']['Info'](arg1);
}

export function InjectPosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InjectPosition'](arg1, arg2, arg3, arg4, arg5);
}

export function InviteFriendToParty(arg1) {
  return window['go']['main']['App']['InviteFriendToParty'](arg1);
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function JoinCentralParty(arg1) {
  return window['go']['main']['App']['JoinCentralParty'](arg1);
}

export function JoinParty(arg1, arg2) {
  return window['go']['main']['App']['JoinParty'](arg1, arg2);
}

export function LeaveCentralParty() {
  return window['go']['main']['App']['LeaveCentralParty']();
}

export function LeaveParty() {
  return window['go']['main']['App']['LeaveParty']();
}

export function OpenMapWindow() {
  return window['go']['main']['App']['OpenMapWindow']();
}

export function OpenReleaseURL() {
  return window['go']['main']['App']['OpenReleaseURL']();
}

export function OpenTarkovDevBrowser() {
  return window['go']['main']['App']['OpenTarkovDevBrowser']();
}

export function RemoveFriend(arg1) {
  return window['go']['main']['App']['RemoveFriend'](arg1);
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectLogsDirectory() {
  return window['go']['main']['App']['SelectLogsDirectory']();
}

export function SelectScreenshotDirectory() {
  return window['go']['main']['App']['SelectScreenshotDirectory']();
}

export function SendPositionToParty(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendPositionToParty'](arg1, arg2, arg3, arg4, arg5);
}

export function SetAutoUpdateCheck(arg1) {
  return window['go']['main']['App']['SetAutoUpdateCheck'](arg1);
}

export function SetManualMapOverride(arg1) {
  return window['go']['main']['App']['SetManualMapOverride'](arg1);
}

export function SetUpdateChannel(arg1) {
  return window['go']['main']['App']['SetUpdateChannel'](arg1);
}

export function StartIntegration() {
  return window['go']['main']['App']['StartIntegration']();
}

export function StartPartyServer() {
  return window['go']['main']['App']['StartPartyServer']();
}

export function StopIntegration() {
  return window['go']['main']['App']['StopIntegration']();
}

export function StopPartyServer() {
  return window['go']['main']['App']['StopPartyServer']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function ValidateQuestToken() {
  return window['go']['main']['App']['ValidateQuestToken']();
}

export function Warning(arg1) {
  return window['go']['main']['App']['Warning'](arg1);
}
